// Mocks generated by Mockito 5.4.6 from annotations
// in store/test/bloc/home_cubit_additional_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:store/core/error/failures.dart' as _i6;
import 'package:store/features/home/data/models/product_model.dart' as _i7;
import 'package:store/features/home/domain/repositories/home_repository.dart'
    as _i2;
import 'package:store/features/home/domain/usecases/delete_product_usecase.dart'
    as _i9;
import 'package:store/features/home/domain/usecases/get_product_list_usecase.dart'
    as _i4;
import 'package:store/features/home/domain/usecases/save_product_usecase.dart'
    as _i8;
import 'package:store/features/home/domain/usecases/update_product_usecase.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHomeRepository_0 extends _i1.SmartFake
    implements _i2.HomeRepository {
  _FakeHomeRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetProductListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductListUseCase extends _i1.Mock
    implements _i4.GetProductListUseCase {
  MockGetProductListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get homeRepository =>
      (super.noSuchMethod(
            Invocation.getter(#homeRepository),
            returnValue: _FakeHomeRepository_0(
              this,
              Invocation.getter(#homeRepository),
            ),
          )
          as _i2.HomeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.ProductModel>> call({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#page: page}),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.ProductModel>>.value(
                  _FakeEither_1<_i6.Failure, _i7.ProductModel>(
                    this,
                    Invocation.method(#call, [], {#page: page}),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.ProductModel>>);
}

/// A class which mocks [SaveProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveProductUseCase extends _i1.Mock
    implements _i8.SaveProductUseCase {
  MockSaveProductUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get homeRepository =>
      (super.noSuchMethod(
            Invocation.getter(#homeRepository),
            returnValue: _FakeHomeRepository_0(
              this,
              Invocation.getter(#homeRepository),
            ),
          )
          as _i2.HomeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call({
    required _i7.Product? product,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#product: product}),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [], {#product: product}),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [DeleteProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteProductUseCase extends _i1.Mock
    implements _i9.DeleteProductUseCase {
  MockDeleteProductUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get homeRepository =>
      (super.noSuchMethod(
            Invocation.getter(#homeRepository),
            returnValue: _FakeHomeRepository_0(
              this,
              Invocation.getter(#homeRepository),
            ),
          )
          as _i2.HomeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call({required String? id}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#id: id}),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [], {#id: id}),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [UpdateProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProductUseCase extends _i1.Mock
    implements _i10.UpdateProductUseCase {
  MockUpdateProductUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get homeRepository =>
      (super.noSuchMethod(
            Invocation.getter(#homeRepository),
            returnValue: _FakeHomeRepository_0(
              this,
              Invocation.getter(#homeRepository),
            ),
          )
          as _i2.HomeRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call({
    required _i7.Product? product,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#product: product}),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [], {#product: product}),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
