// Mocks generated by Mockito 5.4.6 from annotations
// in store/test/bloc/product_detail_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:store/core/error/failures.dart' as _i6;
import 'package:store/features/product_detail/data/models/product_detail_model.dart'
    as _i7;
import 'package:store/features/product_detail/domain/repositories/product_detail_repository.dart'
    as _i2;
import 'package:store/features/product_detail/domain/usecases/get_product_detail_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProductDetailRepository_0 extends _i1.SmartFake
    implements _i2.ProductDetailRepository {
  _FakeProductDetailRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetProductDetailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductDetailUseCase extends _i1.Mock
    implements _i4.GetProductDetailUseCase {
  MockGetProductDetailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductDetailRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProductDetailRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProductDetailRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.ProductDetailModel>> call(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, _i7.ProductDetailModel>
                >.value(
                  _FakeEither_1<_i6.Failure, _i7.ProductDetailModel>(
                    this,
                    Invocation.method(#call, [id]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.ProductDetailModel>>);
}
