// Mocks generated by Mockito 5.4.6 from annotations
// in store/test/usecases/category_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:store/core/error/failures.dart' as _i5;
import 'package:store/features/category/data/models/category_model.dart' as _i6;
import 'package:store/features/category/domain/repositories/category_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i3.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CategoryModel>>>
  getCategoryList() =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryList, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.CategoryModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.CategoryModel>>(
                    this,
                    Invocation.method(#getCategoryList, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.CategoryModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveCategory({
    required _i6.CategoryModel? categoryModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveCategory, [], {
              #categoryModel: categoryModel,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#saveCategory, [], {
                  #categoryModel: categoryModel,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteCategory({
    required int? index,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [], {#index: index}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteCategory, [], {#index: index}),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
